version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: skillswap-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: SkillSwap
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - skillswap-network

  # Backend Server
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: skillswap-server
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/SkillSwap?authSource=admin
      FRONTEND_URL: http://localhost:3000
      JWT_SECRET: your_jwt_secret_key_here
      COOKIE_SECRET: your_cookie_secret_here
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - skillswap-network

  # Frontend Client (for development)
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile.client
    container_name: skillswap-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_SOCKET_URL: http://localhost:5000
    depends_on:
      - server
    networks:
      - skillswap-network

volumes:
  mongodb_data:

networks:
  skillswap-network:
    driver: bridge 